### ISSUE TITLE
How to integrate ReportPortal with .net core with Visual Studio Test Explorer

### ISSUE THREAD

**Issue by ghost** [reportportal/agent-net-vstest#27]
Hi, I want to migrate my tests from .net framework to .net core and I do not understand how to integrate the report portal with my tests. I read readme file and there it is somehow incomprehensibly described flow for .net core. Could you explain me it possible, and if yes, then how we can do it. Thanks!

**Comment by nvborisenko** [comment]
Does `dotnet test -l:ReportPortal` work properly?

**Comment by ghost** [comment]
@nvborisenko Yes, `it works with dotnet test -l:ReportPortal`, but I'm trying to run tests from visual studio with Report portal integration.

**Comment by nvborisenko** [comment]
@OlegYanushkevich please review my Visual Studio settings:
![image](https://user-images.githubusercontent.com/22616990/60844140-1bf0f300-a1e1-11e9-9664-089206cf2d22.png)

If you have the same settings - I have no idea what is wrong.

**Comment by ghost** [comment]
@nvborisenko same settings for my Visual Studio:) I do not know what could be the reason. Thanks for your help.

**Comment by nvborisenko** [comment]
Try to change logging level to diagnostical on the screenshot above. Might we see better error message.

**Comment by nvborisenko** [comment]
@OlegYanushkevich one more idea: verify that you don't have specified environment variables starting with `REPORTPORTAL_`.

**Comment by suszi88** [comment]
I think I had to install ReportPortal.Shared as I was getting same error, although I was not using nUnit

**Comment by antonmalch** [comment]
@suszi88 , @OlegYanushkevich, @nvborisenko  Hi Guys. Wanted to ask ) In the end you solved the problem? Because Looks like i have the same issue now.             
![pic1](https://user-images.githubusercontent.com/61740549/75778170-fdd39680-5d5f-11ea-913e-9fc7c034c1a6.png)
![pic2](https://user-images.githubusercontent.com/61740549/75778177-0035f080-5d60-11ea-920f-25134d45c3e9.png)



[03/03/2020 14:13:02 Diagnostic] RunSettings Content:
<RunSettings>
  <RunConfiguration>
    <TestAdaptersPaths>.</TestAdaptersPaths>
    <ResultsDirectory>C:\Users\antonm\Source\Repos\UnitTestProject1\TestResults</ResultsDirectory>
    <SolutionDirectory>C:\Users\antonm\Source\Repos\UnitTestProject1\</SolutionDirectory>
    <TargetPlatform>X86</TargetPlatform>
    <TargetFrameworkVersion>Framework45</TargetFrameworkVersion>
  </RunConfiguration>&gt;
  <LoggerRunSettings><Loggers><Logger friendlyName="ReportPortal"><Configuration><Launch.Description>Ran from Visual Studio Test Explorer</Launch.Description></Configuration></Logger></Loggers></LoggerRunSettings><RunSettingsDirectory>C:\Users\antonm\Source\Repos\UnitTestProject1\UnitTestProject1</RunSettingsDirectory></RunSettings>
[03/03/2020 14:13:02 Diagnostic] Value of UseSpecifiedAdapterLocations as specified in Tools -> Options: True
[03/03/2020 14:13:02 Diagnostic] Test framework could not be determined for project: C:\Users\antonm\Source\Repos\UnitTestProject1\UnitTestProject1\bin\Debug\netcoreapp2.1\UnitTestProject1.dll because reference path is null for at least one reference: Microsoft.NETCore.App
[03/03/2020 14:13:02 Diagnostic] Value of FallbackToGlobalVsix as specified in Tools -> Options: True
[03/03/2020 14:13:02 Diagnostic] Adapter location settings being used after evaluation: UseSpecifiedAdapterLocations = False, SkipDefaultAdapters = False, AreAllTestContainersCSharpOrVBProjectsOnly = True
[03/03/2020 14:13:04 Diagnostic] Discovering tests in C:\Users\antonm\Source\Repos\UnitTestProject1\UnitTestProject1\ReportPortal.cs
[03/03/2020 14:13:04 Diagnostic] RockSteady initialized with the following extensions:	C:\Users\antonm\.nuget\packages\mstest.testadapter\1.3.2\build\_common\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll

[03/03/2020 14:13:05 Diagnostic] Final RunSettings for the current TestRunCriteria:
<RunSettings>
  <RunConfiguration>
    <TestAdaptersPaths>.</TestAdaptersPaths>
    <ResultsDirectory>C:\Users\antonm\Source\Repos\UnitTestProject1\TestResults</ResultsDirectory>
    <SolutionDirectory>C:\Users\antonm\Source\Repos\UnitTestProject1\</SolutionDirectory>
    <TargetPlatform>X86</TargetPlatform>
    <TargetFrameworkVersion>FrameworkCore10</TargetFrameworkVersion>
    <CollectSourceInformation>False</CollectSourceInformation>
  </RunConfiguration>&gt;
  <LoggerRunSettings><Loggers><Logger friendlyName="ReportPortal"><Configuration><Launch.Description>Ran from Visual Studio Test Explorer</Launch.Description></Configuration></Logger></Loggers></LoggerRunSettings><RunSettingsDirectory>C:\Users\antonm\Source\Repos\UnitTestProject1\UnitTestProject1</RunSettingsDirectory></RunSettings>
[03/03/2020 14:13:08 Error] Microsoft.VisualStudio.TestPlatform.Common.Exceptions.InvalidLoggerException: Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'ReportPortal'.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.TestLoggerManager.Initialize(String runSettings)
   at Microsoft.VisualStudio.TestPlatform.Client.TestPlatform.CreateTestRunRequest(IRequestData requestData, TestRunCriteria testRunCriteria, TestPlatformOptions options)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(IRequestData requestData, TestRunCriteria testRunCriteria, ITestRunEventsRegistrar testRunEventsRegistrar, TestPlatformOptions options)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(TestRunRequestPayload testRunRequestPayload, ITestHostLauncher testHostLauncher, ITestRunEventsRegistrar testRunEventsRegistrar, ProtocolConfig protocolConfig)
   at Microsoft.VisualStudio.TestPlatform.Client.DesignMode.DesignModeClient.<>c__DisplayClass19_0.<StartTestRun>b__0()
[03/03/2020 14:13:08 Diagnostic] Cancel requested, actions left in queue 2, exiting...
[03/03/2020 14:13:08 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=TestExecutionCanceling, operationInProgress=False
[03/03/2020 14:13:08 Diagnostic] TestDiscoveryStats.OperationStateChanged State=TestExecutionCanceling, InProgress=False
[03/03/2020 14:13:08 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetFinished, operationInProgress=False
[03/03/2020 14:13:08 Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetFinished, InProgress=False
[03/03/2020 14:13:08 Diagnostic] ***    Run finished using 'InMemoryUnitTestWriter' ***
[03/03/2020 14:13:08 Informational] ========== Run test finished: 0 run (0:00:05.3267755) ==========
[03/03/2020 14:13:08 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=TestExecutionCancelAndFinished, operationInProgress=False
[03/03/2020 14:13:08 Diagnostic] TestDiscoveryStats.OperationStateChanged State=TestExecutionCancelAndFinished, InProgress=False

**Comment by suszi88** [comment]
@antonmalch I installed the ReportPortal.Shared nuget and it solved the issue. I see that you do not have it

**Comment by nvborisenko** [comment]
`ReportPortal.Shared` package is installed automatically, it's ok that you don't see it in the list of installed packages.

@antonmalch could you please share your test solution and how you execute tests?

**Comment by antonmalch** [comment]
@nvborisenko It's new Project (for testing Report Portal)
![Pic3](https://user-images.githubusercontent.com/61740549/75780742-9b30c980-5d64-11ea-917c-65f4d7c912a1.png)

**Comment by suszi88** [comment]
@antonmalch just for the record, for me running from vs is not working, it will only integrate with report portal while running from cmd, but it's my case, hope you will solve your issue

**Comment by antonmalch** [comment]
Hi, @suszi88 , ok, understood,  thank you

**Comment by nvborisenko** [comment]
Visual Studio 2017?

**Comment by antonmalch** [comment]
Hi, yes
![pic4](https://user-images.githubusercontent.com/61740549/75781645-40986d00-5d66-11ea-826d-b87739e980f1.png)

**Comment by nvborisenko** [comment]
@antonmalch do you have any `ReportPortal.*.log` files in the directory where `sln` or `csproj` file is located, or near with tests assembly?

**Comment by antonmalch** [comment]
@nvborisenko Good morning. Looks like no. I have not ReportPortal.*.log


![image](https://user-images.githubusercontent.com/61740549/75854001-db8d5780-5df7-11ea-80c8-f24de9367d56.png)
![image](https://user-images.githubusercontent.com/61740549/75854016-e21bcf00-5df7-11ea-98f8-8514bf2fb80e.png)

**Comment by nvborisenko** [comment]
Hey @antonmalch @suszi88 @OlegYanushkevich 
I was able to reproduce this issue and found out what was a problem.

Please try to use `v3.0.0-beta.2` version of the package. I suggest to restart VS after upgrading to let VS reload Logger.

> Note: this package is only for the latest ReportPortalv5.

![image](https://user-images.githubusercontent.com/22616990/75875319-83b91580-5e24-11ea-94ee-666566f78a0f.png)

@antonmalch you will get errors, but it will be separate issue (incorrect url parameter in config). Please share your `ReportPortal.*.log` files near with `sln`.

Guys, please report back whether it fixes the issue.

**Comment by antonmalch** [comment]
Hi, 

v3.0.0-beta.2 version of the package - done

But I can't find   ReportPortal.*.log files. This file(s) should installed automatically?

![pic5](https://user-images.githubusercontent.com/61740549/75880132-5f116d80-5e25-11ea-9132-074b2c52ef60.png)




![Pic6](https://user-images.githubusercontent.com/61740549/75880309-b1eb2500-5e25-11ea-8e0f-6f381fc411f0.png)
![pic7](https://user-images.githubusercontent.com/61740549/75880320-b7486f80-5e25-11ea-8775-3c7522078815.png)

**Comment by nvborisenko** [comment]
Will be appeared after tests execution.

**Comment by antonmalch** [comment]
@nvborisenko , I have execute test (from VS) few times and nothing. Still can't find ReportPortal.*.log files.

![pic11](https://user-images.githubusercontent.com/61740549/75883217-54f26d80-5e2b-11ea-8d48-d9c558d79c29.png)

![pic12](https://user-images.githubusercontent.com/61740549/75883225-59b72180-5e2b-11ea-80fb-570f2d665c96.png)

![pic13](https://user-images.githubusercontent.com/61740549/75883246-63d92000-5e2b-11ea-8569-34450dda2f87.png)

![pic14](https://user-images.githubusercontent.com/61740549/75883262-6b98c480-5e2b-11ea-8011-b96fa5793276.png)




[04/03/2020 15:21:14 Diagnostic] About to Enqueue operation 'RunFromContextOperation', hashcode:51164618 
[04/03/2020 15:21:14 Diagnostic] Enqueue operation 'RunFromContextOperation', hashcode:51164618 
[04/03/2020 15:21:14 Diagnostic] Operation left in the the queue: 1
[04/03/2020 15:21:14 Diagnostic] 	'RunFromContextOperation', hashcode:51164618
[04/03/2020 15:21:14 Diagnostic] 

[04/03/2020 15:21:14 Diagnostic] Processing Queue .....
[04/03/2020 15:21:14 Diagnostic] Operation Dequeue : 'RunFromContextOperation'
[04/03/2020 15:21:14 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetStarted, operationInProgress=False
[04/03/2020 15:21:14 Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetStarted, InProgress=False
[04/03/2020 15:21:14 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=ChangeDetectionStarting, operationInProgress=True
[04/03/2020 15:21:14 Diagnostic] TestDiscoveryStats.OperationStateChanged State=ChangeDetectionStarting, InProgress=False
[04/03/2020 15:21:14 Diagnostic] We programmatically start the build in TestWindowHost.UpdateContainer... 
[04/03/2020 15:21:14 Diagnostic] Adding the Project in Project Map for Guid 0d4c4dfd-517d-47b6-953e-15a0869c4686
[04/03/2020 15:21:14 Diagnostic] Time taken for fetching Roslyn supported projects: 0 milliseconds.
[04/03/2020 15:21:14 Diagnostic] After we await the build that programmatically started in TestWindowHost.UpdateContainer... 
[04/03/2020 15:21:14 Diagnostic] Adding the Project in Project Map for Guid 0d4c4dfd-517d-47b6-953e-15a0869c4686
[04/03/2020 15:21:14 Diagnostic] TestContainer update (build) complete : 387 ms
[04/03/2020 15:21:14 Diagnostic] Adding the Project in Project Map for Guid 0d4c4dfd-517d-47b6-953e-15a0869c4686
[04/03/2020 15:21:14 Diagnostic] Adding the Project in Project Map for Guid 0d4c4dfd-517d-47b6-953e-15a0869c4686
[04/03/2020 15:21:14 Diagnostic] Test framework could not be determined for project: C:\Users\antonm\Source\Repos\UnitTestProject1\UnitTestProject1\bin\Debug\netcoreapp2.1\UnitTestProject1.dll because reference path is null for at least one reference: Microsoft.NETCore.App
[04/03/2020 15:21:14 Diagnostic] DiscoveryOperation<RunFromContextOperation> FinishedChangedCotainers, changed container count is 0
[04/03/2020 15:21:14 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=ChangeDetectionFinished, operationInProgress=False
[04/03/2020 15:21:14 Diagnostic] TestDiscoveryStats.OperationStateChanged State=ChangeDetectionFinished, InProgress=False
[04/03/2020 15:21:14 Informational] Executing test method 'UnitTestProject1.ReportPortal.Test_1111_TestReportPortal'
[04/03/2020 15:21:14 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=TestExecutionStarting, operationInProgress=False
[04/03/2020 15:21:14 Diagnostic] TestDiscoveryStats.OperationStateChanged State=TestExecutionStarting, InProgress=False
[04/03/2020 15:21:14 Informational] ------ Run test started ------
[04/03/2020 15:21:14 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=TestExecutionStarted, operationInProgress=False
[04/03/2020 15:21:14 Diagnostic] TestDiscoveryStats.OperationStateChanged State=TestExecutionStarted, InProgress=False
[04/03/2020 15:21:14 Diagnostic] RunSettings Content:
<RunSettings>
  <RunConfiguration>
    <TestAdaptersPaths>.</TestAdaptersPaths>
    <ResultsDirectory>C:\Users\antonm\Source\Repos\UnitTestProject1\TestResults</ResultsDirectory>
    <SolutionDirectory>C:\Users\antonm\Source\Repos\UnitTestProject1\</SolutionDirectory>
    <TargetPlatform>X86</TargetPlatform>
    <TargetFrameworkVersion>Framework45</TargetFrameworkVersion>
  </RunConfiguration>&gt;
  <LoggerRunSettings><Loggers><Logger friendlyName="ReportPortal"><Configuration><Launch.Description>Ran from Visual Studio Test Explorer</Launch.Description></Configuration></Logger></Loggers></LoggerRunSettings><RunSettingsDirectory>C:\Users\antonm\Source\Repos\UnitTestProject1\UnitTestProject1</RunSettingsDirectory></RunSettings>
[04/03/2020 15:21:14 Diagnostic] Value of UseSpecifiedAdapterLocations as specified in Tools -> Options: True
[04/03/2020 15:21:14 Diagnostic] Value of FallbackToGlobalVsix as specified in Tools -> Options: True
[04/03/2020 15:21:14 Diagnostic] Adapter location settings being used after evaluation: UseSpecifiedAdapterLocations = False, SkipDefaultAdapters = False, AreAllTestContainersCSharpOrVBProjectsOnly = True
[04/03/2020 15:21:15 Diagnostic] Final RunSettings for the current TestRunCriteria:
<RunSettings>
  <RunConfiguration>
    <TestAdaptersPaths>.</TestAdaptersPaths>
    <ResultsDirectory>C:\Users\antonm\Source\Repos\UnitTestProject1\TestResults</ResultsDirectory>
    <SolutionDirectory>C:\Users\antonm\Source\Repos\UnitTestProject1\</SolutionDirectory>
    <TargetPlatform>X86</TargetPlatform>
    <TargetFrameworkVersion>FrameworkCore10</TargetFrameworkVersion>
    <CollectSourceInformation>False</CollectSourceInformation>
  </RunConfiguration>&gt;
  <LoggerRunSettings><Loggers><Logger friendlyName="ReportPortal"><Configuration><Launch.Description>Ran from Visual Studio Test Explorer</Launch.Description></Configuration></Logger></Loggers></LoggerRunSettings><RunSettingsDirectory>C:\Users\antonm\Source\Repos\UnitTestProject1\UnitTestProject1</RunSettingsDirectory></RunSettings>
[04/03/2020 15:21:16 Diagnostic] Discovering tests in C:\Users\antonm\Source\Repos\UnitTestProject1\UnitTestProject1\ReportPortal.cs
[04/03/2020 15:21:16 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetFinished, operationInProgress=False
[04/03/2020 15:21:16 Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetFinished, InProgress=False
[04/03/2020 15:21:16 Error] Microsoft.VisualStudio.TestPlatform.Common.Exceptions.InvalidLoggerException: Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'ReportPortal'.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.TestLoggerManager.Initialize(String runSettings)
   at Microsoft.VisualStudio.TestPlatform.Client.TestPlatform.CreateTestRunRequest(IRequestData requestData, TestRunCriteria testRunCriteria, TestPlatformOptions options)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(IRequestData requestData, TestRunCriteria testRunCriteria, ITestRunEventsRegistrar testRunEventsRegistrar, TestPlatformOptions options)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(TestRunRequestPayload testRunRequestPayload, ITestHostLauncher testHostLauncher, ITestRunEventsRegistrar testRunEventsRegistrar, ProtocolConfig protocolConfig)
   at Microsoft.VisualStudio.TestPlatform.Client.DesignMode.DesignModeClient.<>c__DisplayClass19_0.<StartTestRun>b__0()
[04/03/2020 15:21:16 Diagnostic] Cancel requested, actions left in queue 2, exiting...
[04/03/2020 15:21:16 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=TestExecutionCanceling, operationInProgress=False
[04/03/2020 15:21:16 Diagnostic] TestDiscoveryStats.OperationStateChanged State=TestExecutionCanceling, InProgress=False
[04/03/2020 15:21:16 Diagnostic] ***    Run finished using 'InMemoryUnitTestWriter' ***
[04/03/2020 15:21:16 Informational] ========== Run test finished: 0 run (0:00:01.7459409) ==========
[04/03/2020 15:21:16 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=TestExecutionCancelAndFinished, operationInProgress=False
[04/03/2020 15:21:16 Diagnostic] TestDiscoveryStats.OperationStateChanged State=TestExecutionCancelAndFinished, InProgress=False

**Comment by nvborisenko** [comment]
@antonmalch  And have you restarted Visual Studio?

**Comment by antonmalch** [comment]
@nvborisenko Yes

**Comment by nvborisenko** [comment]
I also see issues on clean environment with VS2017 and .netcore2.1, sometimes I saw different issues, It depends on @DzmitryHumianiuk  how much we want to invest to resolve the issue.

**Comment by DzmitryHumianiuk** [comment]
@nvborisenko it's hard for to evaluate something in .net world.
So i should rely on you here.

**Comment by jsingh-qualitrol** [comment]
@nvborisenko @antonmalch  have you got solution to the problem? I am also getting the same error with latest v3.0.0-beta.3.Please help

**Comment by nvborisenko** [comment]
@jsingh-qualitrol VS 2017?

**Comment by jsingh-qualitrol** [comment]
No i am using VS 2019

**Comment by nvborisenko** [comment]
https://github.com/reportportal/agent-net-vstest#visual-studio-test-explorer

did you try it?

**Comment by jsingh-qualitrol** [comment]
yes i followed the same steps mentioned in the link. @nvborisenko

**Comment by nvborisenko** [comment]
https://github.com/reportportal/example-net-vstest please play with this pre-configured project.

**Comment by nvborisenko** [comment]
@jsingh-qualitrol please share a project you have played with.

**Comment by nvborisenko** [comment]
Reproduced it again on my side. Working solution is specifying full path to output folder (bin\Debug) in runsettings file, TestAdaptersPaths property.

**Comment by BilalKhan199** [comment]
Update: first time you have to provide full path, then it works without providing full path, I'm using VS2019

**Comment by nvborisenko** [comment]
And finally the root cause of the issue is relative path specified in `runsettings` file. Official way is to use `.` (current directory) as a location where VS (or any other test runner) should search for test adapter (test logger). Since this is relative path, the question is relative to what.

When we execute tests in Visual Studio, then my finding is relative path to Visual Studio directory where VS was run from.

If I start VS from Windows task bar, the current directory is `C:\\Program Files\\...`. And, VS runner cannot find test logger. But if I open solution file in File Explorer (double click on `*.sln`) then current directory for VS is the directory where `*.sln` file is located. In this case VS is able to find test logger in project's `bin/Debug` directory.

Thus, for all who is experiencing this issue, please open your solution file using double click in File Explorer.

This issue cannot be considered as resolved, let's see what MS swill say.
